import torch
import torchcde
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
from coral_model import CoralSTGNCDE
from data_utils import build_augmented_input, normalize_adjacency
from config import *

def main():
    print("--- GENERATING VISUALIZATIONS ---")
    os.makedirs(PLOT_DIR, exist_ok=True)
    
    # 1. Load Data
    print("Loading Data...")
    if not os.path.exists(f"{DATA_DIR}X.pt"):
        print("Error: processed data not found.")
        return

    X_raw = torch.load(f"{DATA_DIR}X.pt").float()
    y = torch.load(f"{DATA_DIR}y.pt").float()
    mask = torch.load(f"{DATA_DIR}mask.pt").float()
    adj = torch.load(f"{DATA_DIR}adjacency_matrix.pt").float()

    adj = normalize_adjacency(adj)

    site_list = pd.read_csv(f"{DATA_DIR}site_list.csv")
    
    num_sites, num_times, input_features = X_raw.shape
    
    # Dynamic Date
    # Load the exact dates generated by the data pipeline
    dates_df = pd.read_csv(f"{DATA_DIR}time_dates.csv")
    time_dates = pd.to_datetime(dates_df['Date']).values
    
    # Prepare Inputs
    SPLIT_IDX = int(num_times * TRAIN_SPLIT)
    X_augmented, _, _ = build_augmented_input(X_raw, y, mask, SPLIT_IDX, decay_rate=DECAY_RATE)

    input_features = X_augmented.shape[-1]

    X_time_first = X_augmented.permute(1, 0, 2)
    X_flat = X_time_first.reshape(num_times, -1).to(DEVICE)
    
    coeffs = torchcde.linear_interpolation_coeffs(X_flat)
    
    # 3. Load Model
    print(f"Loading Model: {MODEL_PATH}")
    model = CoralSTGNCDE(
        num_sites=num_sites,
        input_features=input_features,
        hidden_dim=HIDDEN_DIM,
        output_features=1,
        adj_matrix=adj
    ).to(DEVICE)
    
    try:
        model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
    except FileNotFoundError:
        print(f"Error: {MODEL_PATH} not found.")
        return
        
    model.eval()
    
    # 4. Run Prediction
    print("Running Inference...")
    with torch.no_grad():
        pred = model(coeffs) 
    
    y_np = y.squeeze(-1).numpy()
    pred_np = pred.permute(1, 0, 2).squeeze(-1).cpu().numpy()
    mask_np = mask.squeeze(-1).numpy()
    
    split_date = time_dates[int(num_times * 0.8)] 
    
   # 5. Plotting Loop
    print(f"Saving plots to {PLOT_DIR}...")
    
    # Extract the raw environmental data (to get the real DHW values)
    X_env = X_raw.numpy()
    
    for i in range(num_sites):
        site_name = site_list.iloc[i]['Site_ID']
        
        site_y = y_np[i, :]
        site_pred = pred_np[i, :]
        site_mask = mask_np[i, :]
        site_dhw = X_env[i, :, 1] # Index 1 is DHW, Index 0 is SST
        
        valid_indices = np.where(site_mask > 0)[0]
        valid_time = time_dates[valid_indices] 
        valid_y = site_y[valid_indices]
        
        fig, ax1 = plt.subplots(figsize=(12, 6))
        
        # --- PRIMARY AXIS (Left): Biology ---
        ax1.plot(time_dates, site_pred, color='blue', label='AI Prediction', linewidth=2.0, alpha=0.8)
        
        # Plot Ground Truth as a clean line (Removed the scatter dots)
        ax1.plot(valid_time, valid_y, color='red', label='Observed Coral Cover', linestyle='-', linewidth=1.5, alpha=0.8)
        
        ax1.axvline(x=split_date, color='black', linestyle='--', alpha=0.5, label='Train / Test Split')
        
        # --- SECONDARY AXIS (Right): Environment ---
        ax2 = ax1.twinx()
        
        # Plot DHW as a clean line graph (Removed the shaded fill)
        ax2.plot(time_dates, site_dhw, color='darkorange', label='Degree Heating Weeks', linewidth=1.5, alpha=0.9, linestyle='-')
        
        ax2.set_ylabel("DHW (°C-weeks)", color='darkorange', fontweight='bold')
        ax2.tick_params(axis='y', labelcolor='darkorange')
        
        # Scale the secondary axis so the DHW spikes don't overlap the coral lines too much
        max_dhw = np.max(site_dhw) if np.max(site_dhw) > 5 else 5
        ax2.set_ylim(0, max_dhw * 2.5)
        
        # --- FORMATTING & LEGEND ---
        plt.title(f"Site: {site_name}", fontsize=14, fontweight='bold')
        plt.xlim(time_dates[0], time_dates[-1])
        
        # Combine legends from both axes
        lines_1, labels_1 = ax1.get_legend_handles_labels()
        lines_2, labels_2 = ax2.get_legend_handles_labels()
        ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='upper left')
        
        # Save
        safe_name = str(site_name).replace("/", "_").replace(" ", "_")
        plt.savefig(f"{PLOT_DIR}{safe_name}.png", bbox_inches='tight')
        plt.close()
        
        if (i+1) % 10 == 0:
            print(f"   Plotting {i+1}/{num_sites}...")

    print("Done! Check the 'results/plots/' folder.")

if __name__ == "__main__":
    main()